name: andiamo
description: andIAmo — l'app per scoprire dove uscire stasera.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Routing
  go_router: ^14.6.0

  # Networking
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0

  # Models
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2

  # Maps (OSM tiles)
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1

  # UI
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  palette_generator: ^0.3.3+5

  # Media
  image_picker: ^1.1.2

  # Typography
  google_fonts: ^6.2.1

  # External actions
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.4.3
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  custom_lint: ^0.7.0
  riverpod_lint: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
