"""create outing_votes

Revision ID: 09bf4f51af77
Revises: 1d275b8556a6
Create Date: 2026-05-08 00:09:46.355222

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09bf4f51af77'
down_revision: str | Sequence[str] | None = '1d275b8556a6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outing_votes',
    sa.Column('outing_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('locale_id', sa.Uuid(), nullable=False),
    sa.Column('vote', sa.String(length=8), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("vote IN ('like', 'dislike')", name='ck_outing_votes_value'),
    sa.ForeignKeyConstraint(['locale_id'], ['locales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outing_id'], ['outings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('outing_id', 'user_id', 'locale_id', name='uq_outing_votes_unique')
    )
    op.create_index(op.f('ix_outing_votes_locale_id'), 'outing_votes', ['locale_id'], unique=False)
    op.create_index(op.f('ix_outing_votes_outing_id'), 'outing_votes', ['outing_id'], unique=False)
    op.create_index(op.f('ix_outing_votes_user_id'), 'outing_votes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outing_votes_user_id'), table_name='outing_votes')
    op.drop_index(op.f('ix_outing_votes_outing_id'), table_name='outing_votes')
    op.drop_index(op.f('ix_outing_votes_locale_id'), table_name='outing_votes')
    op.drop_table('outing_votes')
    # ### end Alembic commands ###
