"""create recommendation_logs

Revision ID: 4dc7f7b058e9
Revises: 448f64690e6f
Create Date: 2026-05-07 17:14:52.446439

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4dc7f7b058e9'
down_revision: str | Sequence[str] | None = '448f64690e6f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_logs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('requested_lat', sa.Float(), nullable=True),
    sa.Column('requested_lng', sa.Float(), nullable=True),
    sa.Column('locale_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_logs_user_id'), 'recommendation_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_logs_user_id'), table_name='recommendation_logs')
    op.drop_table('recommendation_logs')
    # ### end Alembic commands ###
