"""add phone website to locales

Revision ID: ff2356ea2a1c
Revises: 09bf4f51af77
Create Date: 2026-05-08 01:05:03.501014

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff2356ea2a1c'
down_revision: str | Sequence[str] | None = '09bf4f51af77'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locales', sa.Column('phone', sa.String(length=32), nullable=True))
    op.add_column('locales', sa.Column('website', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locales', 'website')
    op.drop_column('locales', 'phone')
    # ### end Alembic commands ###
