"""create outings and outing_participants

Revision ID: c8a40773d0e7
Revises: 49505b035550
Create Date: 2026-05-07 17:50:11.632082

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a40773d0e7'
down_revision: str | Sequence[str] | None = '49505b035550'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outings',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('when_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('chosen_locale_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('planning', 'decided', 'done', 'cancelled')", name='ck_outings_status'),
    sa.ForeignKeyConstraint(['chosen_locale_id'], ['locales.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outings_owner_id'), 'outings', ['owner_id'], unique=False)
    op.create_table('outing_participants',
    sa.Column('outing_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['outing_id'], ['outings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('outing_id', 'user_id', name='uq_outing_participants')
    )
    op.create_index(op.f('ix_outing_participants_outing_id'), 'outing_participants', ['outing_id'], unique=False)
    op.create_index(op.f('ix_outing_participants_user_id'), 'outing_participants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outing_participants_user_id'), table_name='outing_participants')
    op.drop_index(op.f('ix_outing_participants_outing_id'), table_name='outing_participants')
    op.drop_table('outing_participants')
    op.drop_index(op.f('ix_outings_owner_id'), table_name='outings')
    op.drop_table('outings')
    # ### end Alembic commands ###
