"""create outing_messages

Revision ID: 0512243722d7
Revises: ff2356ea2a1c
Create Date: 2026-05-08 01:08:08.877074

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0512243722d7'
down_revision: str | Sequence[str] | None = 'ff2356ea2a1c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outing_messages',
    sa.Column('outing_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('text', 'system', 'ai')", name='ck_outing_messages_kind'),
    sa.ForeignKeyConstraint(['outing_id'], ['outings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outing_messages_outing_id'), 'outing_messages', ['outing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outing_messages_outing_id'), table_name='outing_messages')
    op.drop_table('outing_messages')
    # ### end Alembic commands ###
