"""add embedding to user_preferences

Revision ID: 448f64690e6f
Revises: c22d980a4060
Create Date: 2026-05-07 17:07:58.995931

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '448f64690e6f'
down_revision: str | Sequence[str] | None = 'c22d980a4060'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'embedding')
    # ### end Alembic commands ###
