"""create locales, media, opening_hours

Revision ID: e5d7e1dfe520
Revises: 677155d710a9
Create Date: 2026-05-07 16:40:10.519678

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'e5d7e1dfe520'
down_revision: str | Sequence[str] | None = '677155d710a9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locales',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('price_level', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('bar', 'ristorante', 'pub', 'pizzeria', 'caffe', 'club')", name='ck_locales_type'),
    sa.CheckConstraint('price_level BETWEEN 1 AND 4', name='ck_locales_price_level'),
    sa.PrimaryKeyConstraint('id')
    )
    # idx_locales_location is created automatically by GeoAlchemy on the Geometry column
    op.create_index(op.f('ix_locales_city'), 'locales', ['city'], unique=False)
    op.create_index(op.f('ix_locales_type'), 'locales', ['type'], unique=False)
    op.create_table('locale_media',
    sa.Column('locale_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['locale_id'], ['locales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locale_media_locale_id'), 'locale_media', ['locale_id'], unique=False)
    op.create_table('opening_hours',
    sa.Column('locale_id', sa.Uuid(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=False),
    sa.Column('close_time', sa.Time(), nullable=False),
    sa.Column('closed_all_day', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name='ck_opening_hours_weekday'),
    sa.ForeignKeyConstraint(['locale_id'], ['locales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('locale_id', 'weekday', name='uq_opening_hours_locale_weekday')
    )
    op.create_index(op.f('ix_opening_hours_locale_id'), 'opening_hours', ['locale_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opening_hours_locale_id'), table_name='opening_hours')
    op.drop_table('opening_hours')
    op.drop_index(op.f('ix_locale_media_locale_id'), table_name='locale_media')
    op.drop_table('locale_media')
    op.drop_index(op.f('ix_locales_type'), table_name='locales')
    op.drop_index(op.f('ix_locales_city'), table_name='locales')
    op.drop_table('locales')
    # ### end Alembic commands ###
